baseURL: "https://angelosantos.github.io/" 
title: Angelo Santos 
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 
        - name: Newsletter
          url: https://pmichaillat.substack.com
          weight: 4

params:
    description: ""
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Angelo Santos
          subtitle: "Hello! I am a PhD candidate at the University of Houston. My interest are development, education and health. In my current research, I analyze the impacts of a special education policy in Brazil. I am also a python and soccer lover!"
          imageUrl: "profile_square.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Angelo Santos
          buttons:
            # - name: Papers
            #   url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
              # url: tags/
            # - name: Archive
            #   url: archive/
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
    socialIcons:
        - name: CV
          url: angelosantos_cv.pdf
        - name: Email
          url: mailto:afdossan@cougarnet.uh.edu
        - name: Linkedin
          url: https://www.linkedin.com/in/angelo-santos-2854bb147/
        # - name: Office Hours
        #   url: officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/AngeloSant0s
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Twitter
        #   url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Angelo Santos"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
